name: "Build all images with default"
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build all
        run: nix flake check --print-build-logs --show-trace --verbose
      - name: Size summary
        run: nix run .#docker-size-summary